#
#	web-dynamic -- Makefile to use Ioto as a web-server for dynamic requests
#

include ../defines.mk

all: sample

sample: sample.o

sample.o: sample.c

run:
	./sample

clean:
	rm -f sample.o sample
