#
#	own-main/Makefile -- Makefile to use Ioto as a library and provide own main()
#

include ../defines.mk

all: sample

sample: sample.o

sample.o: sample.c

run:
	./sample

clean:
	rm -f sample.o sample
